### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by yuhui-xie** [UMich-BipedLab/optimal_shape_generation#1]
Hi, it's very nice to see your work, I have tried to use your code, but a exception about path doesn't exist has been throw, I find that it is in the file: loadLibraries, with line 34-40
`            opts.path.intrinsic_lib = opts.path.root_path + "lc-calibration/LiDAR_intrinsic_calibration";
            opts.path.extrinsic_lib = opts.path.root_path + "lc-calibration/extrinsic_lidar_camera_calibration/extrinsic_utils";
            opts.path.simulator_lib = opts.path.root_path + "lc-calibration/lidar_simulator";
            opts.path.utils = opts.path.root_path + "matlab_utils";
            opts.path.tag_placement_lib = opts.path.simulator_lib + "/tag_placement";
            opts.path.noise_lib = opts.path.simulator_lib + "/noise";
            opts.path.scenes_dir = opts.path.simulator_lib + "/scenes";`
How can I find 'lc-calibration/LiDAR_intrinsic_calibration', 'lc-calibration/extrinsic_lidar_camera_calibration/extrinsic_utils', and 'lc-calibration/lidar_simulator'?

**Comment by yuhui-xie** [comment]
I find those file in your repo, but a new error occur, that is can't find 'plotShape' function. 
I run the file projective_vs_convexity2.m.
May I ask How can I solve this?

**Comment by brucejk** [comment]
Hi, 

Thank you for using this repo! 

1. You actually do not need the `loadLibraries` file, for which you can directly comment out. 

2. I have updated the [matlab_utils](https://github.com/UMich-BipedLab/matlab_utils)

Please let me know if you encounter any other issues!
